### ISSUE TITLE
nitro panics on errors in core.ApplyTransaction

### ISSUE THREAD

**Issue by schmir-at-bb** [shutter-network/rolling-shutter#311]
This error happened while working on #295. `core.ApplyTransaction` returns an error and as a result the sequencer panics.
This looks like a bug in nitro to me. 

```
sequencer_1         | INFO [07-25|07:24:44.787] error in core.ApplyTransaction           tx="&{inner:0xc00123ca80 time:{wall:13884508793391269089 ext:262845290524 loc:0x26c9000} PosterCost:+39132812112 PosterIsReimbursable:true hash:{v:[234 206 170 76 195 161 0 248 56 45 98 246 196 61 147 227 175 167 222 134 238 134 142 251 153 96 43 126 29 87 108 209]} size:{v:79} from:{v:<nil>}}" err="decryption key is invalid"
sequencer_1         | panic: revision id 1 cannot be reverted
sequencer_1         | 
sequencer_1         | goroutine 87 [running]:
sequencer_1         | github.com/ethereum/go-ethereum/core/state.(*StateDB).RevertToSnapshot(0xc00176e380, 0x1)
sequencer_1         |   /workspace/go-ethereum/core/state/statedb.go:782 +0x2c5
sequencer_1         | github.com/offchainlabs/nitro/arbos.ProduceBlockAdvanced.func1({0x1b50bf8, 0xc0019bde90}, 0xc00123ca10, 0xc0020955a0, 0xc002095780, 0xc002095e48, 0xc001d4b340, 0xc000481ca0, 0xc002095550, {0xa4, ...}, ...)
sequencer_1         |   /workspace/arbos/block_processor.go:259 +0x61a
sequencer_1         | github.com/offchainlabs/nitro/arbos.ProduceBlockAdvanced(0xc0012175c0, {0xc0009448a0, 0x1, 0xc000488078}, 0x2, 0xc0000c2d20, 0xc00176e380, {0x1b2f488, 0xc000281800}, 0xc0000ee900, ...)
sequencer_1         |   /workspace/arbos/block_processor.go:269 +0x970
sequencer_1         | github.com/offchainlabs/nitro/arbnode.(*TransactionStreamer).SequenceTransactions(0xc00013d590, 0xc000481b20, {0xc0009448a0, 0x1, 0x1}, 0xc002095e48)
sequencer_1         |   /workspace/arbnode/transaction_streamer.go:467 +0x3d3
sequencer_1         | github.com/offchainlabs/nitro/arbnode.(*Sequencer).sequenceTransactions(0xc000271d90, {0x1b4a158, 0xc0004542c0})
sequencer_1         |   /workspace/arbnode/sequencer.go:236 +0x930
sequencer_1         | github.com/offchainlabs/nitro/arbnode.(*Sequencer).Start.func2({0x1b4a158, 0xc0004542c0})
sequencer_1         |   /workspace/arbnode/sequencer.go:331 +0x5d
sequencer_1         | github.com/offchainlabs/nitro/util/stopwaiter.(*StopWaiterSafe).CallIteratively.func1({0x1b4a158, 0xc0004542c0})
sequencer_1         |   /workspace/util/stopwaiter/stopwaiter.go:127 +0x4d
sequencer_1         | github.com/offchainlabs/nitro/util/stopwaiter.(*StopWaiterSafe).LaunchThread.func1()
sequencer_1         |   /workspace/util/stopwaiter/stopwaiter.go:111 +0x2e
sequencer_1         | created by github.com/offchainlabs/nitro/util/stopwaiter.(*StopWaiterSafe).LaunchThread
sequencer_1         |   /workspace/util/stopwaiter/stopwaiter.go:110 +0xe9
shutter-nitro_sequencer_1 exited with code 2

```

**Comment by jannikluhn** [comment]
Does this happen with a correct or with an invalid decryption key?

**Comment by schmir-at-bb** [comment]
This happens when the decryption key is invalid.

**Comment by jannikluhn** [comment]
closing because we're using the mock sequencer now
